apiVersion: "v1"
kind: "LimitRange"
metadata:
 name: "resource-limits-tcs-project"
spec:
 limits: 
   - type: "Pod"
     max:
       cpu: "500m"
       memory: "512Mi"
     min:
       cpu: "20m"
       memory: "20Mi"
   - type: "Container"
     max:
       cpu: "500m"
       memory: "512Mi"
     min:
       cpu: "20m"
       memory: "20Mi"
